number_of_topics:
  default: 5
  min: 1
  max: 5
  description: Display up to 5 topics at max-width

show_on:
  default: homepage
  type: enum
  choices:
    - top_menu
    - homepage
    - all
  description: top_menu refers to pages set in the <a href="/admin/site_settings/category/all_results?filter=top_menu">top menu site setting</a>

show_for:
  default: everyone
  type: enum
  choices:
    - everyone
    - logged_in
    - logged_out

show_title:
  default: true
  description: displays the text set below

title_text:
  default: "Trending"

topic_source:
  type: enum
  default: "top/all"
  choices:
    - latest
    - top/all
    - top/yearly
    - top/quarterly
    - top/monthly
    - top/weekly
    - top/daily

sort_by_created:
  default: true
  description: Disable to sort by latest activity

display_mobile: false

featured_content_position:
  default: discovery_list_controls_above
  type: enum
  choices:
    - above_main_container
    - below_discovery_categories
    - discovery_list_controls_above
  description: Advanced theme development&colon; this changes the plugin outlet for the component
